#!/usr/bin/env zsh

# Load zplug
source "$ZPLUG_HOME/init.zsh"

# Load plugins
zplug 'Aloxaf/fzf-tab', depth:1
zplug "adriangalilea/homebrew-ip", use:"magic_dashboard.sh", as:command
zplug 'zsh-users/zsh-syntax-highlighting', depth:1
zplug 'junegunn/fzf-git.sh', as:command, use:'fzf-git.sh', depth:1
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "MichaelAquilina/zsh-you-should-use"
zplug "chrisgrieser/zsh-magic-dashboard", use:"magic_dashboard.zsh"
zplug "betafcc/nav", use:"nav.zsh"
# zplug 'sobolevn/sobole-zsh-theme', as:theme, depth:1
zplug "romkatv/powerlevel10k", as:theme, depth:1

# Install plugins if there are plugins that have not been installed
if ! zplug check; then
    zplug install
fi

# Configure nav plugin
bindkey '^[[1;2A' nav-up      # shift + up
bindkey '^[[1;2B' nav-down    # shift + down
bindkey '^[[1;2C' nav-forward # shift + right
bindkey '^[[1;2D' nav-back    # shift + left

# Load zplug plugins
zplug load
