#!/usr/bin/env bash

export ZSH_HIGHLIGHT_MAXLENGTH=200     # limit zsh-highlight for performance
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export LESSHISTFILE="$XDG_DATA_HOME/less/lesshst"

# Function to safely add directories to PATH
path_append() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="${PATH:+"$PATH:"}$1"
    fi
}

path_append "$HOME/.local/bin"         # XDG path for bins
path_append "$HOME/bin"                # mpv
path_append "$HOME/bin/x"              # x/twitter from the terminal

# Golang
export GOPATH="$HOME/.local/go"
path_append "$GOPATH/bin"

# Rust -> Cargo
export PATH="$HOME/.cargo/bin:$PATH"

# Bun
export BUN_INSTALL="$HOME/.local/bun"
path_append "$BUN_INSTALL/bin"

# Python and pipx
if [[ "$(uname -s)" == "Darwin" ]]; then
    path_append "$(brew --prefix python)/libexec/bin"
else
    path_append "$HOME/.local/bin"  # pipx on linux
fi

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
path_append "$PNPM_HOME"

# Ensure PATH is exported
export PATH
