# in order to let my rpi not die from shellcheck
[[language]]
name = "bash"
language-servers = []

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls", "emmet-ls", "vale" ]
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls", "emmet-ls", "vale" ]
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls", "eslint", "emmet-ls", "vale" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "eslint", "emmet-ls", "tailwindcss-ls", "vale" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "eslint", "emmet-ls", "tailwindcss-ls", "vale" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "eslint", "emmet-ls", "vale" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "prettier", args = [ "--parser", "json" ] }
auto-format = true

[[language]]
name = "markdown"
language-servers = [{ name = "ltex"}, "markdown-oxide", "vale"] #prev marksman
file-types = ["md", "txt"]
scope = "text.markdown"
roots = []

[[language]]
name = "python"
language-servers = [ "pylsp", "vale" ]
formatter = { command = "black" }
auto-format = true

[language-server]
emmet-ls = { command = "emmet-ls", args = [ "--stdio" ]}

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = false }

[language-server.vscode-json-language-server.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[language-server.vscode-css-language-server.config]
css = { validate = { enable = true } }
scss = { validate = { enable = true } }
less = { validate = { enable = true } }
provideFormatter = true


# [language-server.ltex]
# command = "/usr/local/bin/ltex-ls"

# [language-server.ltex.config.ltex.dictionary]
# "en-US" = ["Tp-Note","Zettelkasten"]

# [language-server.gpt]
# command = "helix-gpt"
# environment = { HANDLER= "copilot" }


[language-server.vale]
command = "vale-ls"
